language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  # - "3.8-dev"  # 3.8 development branch
  # - "nightly"  # nightly build
# command to install dependencies
jobs:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.0 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.0 on Windows"
      os: windows        
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest